version: '3'
services:
  front-end:
    build: todo-app/front-end
    restart: on-failure
    depends_on:
      - back-end
    ports: 
      - 3000:3000

  back-end: 
    build: todo-app/back-end
    environment:
      - DB_HOST: tests 
    depends_on:
      - tests
    ports:
      - 3001:3001
    restart: on-failure

  tests:
    image: alpine:3.12
    restart: on-failure
 